//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEmployeeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EmpDetails
    {
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public long EmpId { get; set; }
    }
}
